export enum GetEndpointUrl {
    Logout = "/logout",
    SelfProfile = "/user/profile",
    SelfProfileSideNav = "/user/sidebarNav",
    UserListNotBelongToChannel = "user/usersListNotBelongToChannelId",
    CheckTeamNameAvailability = "/team/checkTeamNameExist",
    TeamListUserIsAdmin = "/team/teamListByAdminUID",
    CheckChannelNameAvailability = "/ch/chNameIsAvailable",
    ChannelBasicInfo = "/ch/channelBasicInfo",
    ChannelMemberInfoWithAdminFlagInfo = "/ch/channelInfoWithMemberAdminFlag",
    PublicAttachmentURL = "/getFile",
    GetChannelMedia = "/ch/getFile",
    GetChannelLatestPost = "/po/latestPosts",
    GetChatLatestMessage = "/dm/latestChat",
    GetNewPostIncludingCurrentPost = "/po/newPostsIncludingCurrent",
    GetNewChatIncludingCurrentChat = "/dm/newChatsIncludingCurrentChat",
    GetNewPostAfter = "/po/newPosts",
    GetNewChatAfter = "/dm/newChats",
    GetOldPostBefore = "/po/oldPosts",
    GetOldChatBefore = "/dm/oldChats",
    GetChatMedia = "/dm/getFile",
    GetOnlyPostText = "/po/getOnlyPostText",
    GetOnlyChatText = "/dm/getChatOnlyText",
    GetUserStatuses = "/user/getAllUserEmojiStatusList",
    GetUserEmojiStatus = "/user/getActiveUserEmojiStatus",
    GetPostWithAllComments = "/po/allComments",
    GetChatWithAllComments = "/dm/chatWithAllComments",
    GetMqttConfig = "/config/getMqttConfig",
    GetUserLatestChatList = "/dm/getLatestChatList",
    GetAllUser = "/user/allUsers",
    GetUserActiveChannelList = "/ch/userActiveChannelsWithLatestPost",
    GetUserArchiveChannelList = "/ch/userArchiveChannelsWithLatestPost",
}

export enum PostFileUploadURL {
    UploadFile = "/uploadFile",
}

export enum PostEndpointUrl {
    CreateTeam = "/team/createTeam",
    CreateProject = "/project/createProject",
    CreateChannel = "/ch/create",
    JoinChannel = "/ch/joinChannel",
    UpdateChannel = "/ch/updateInfo",
    RemoveChannelModerator = "/ch/removeModerator",
    RemoveChannelMember = "/ch/removeMember",
    AddChannelModerator = "/ch/addModerator",
    AddChannelMember = "/ch/addMember",
    AddFavChannel = "/user/addFavChannel",
    RemoveFavChannel = "/user/removeFavChannel",
    UpdateChannelNotification = "/user/updateUserChannelNotification",
    UpdateChatNotification = "/user/updateChatNotification",
    CreateChannelPost = "/po/createPost",
    CreateChatMessage = "/dm/createChat",
    DeleteChannelPost = "/po/deletePost",
    DeleteChatMessage = "/dm/deleteChat",
    UpdateChannelPost = "/po/updatePost",
    UpdateChatMessage = "/dm/updateChat",
    SearchUserAndChannel = "/user/searchUserAndChannelList",
    FwdMsgToChatOrChannel = "/user/fwdMessage",
    UpdateUserEmojiStatus = "/user/updateStatusEmojiStatus",
    ClearEmojiStatus = "/user/clearUserEmojiStatus",
    CreatePostComment = "/po/createComment",
    CreateChatComment = "/dm/createComment",
    UpdatePostComment = "/po/updateComment",
    UpdateChatComment = "/dm/updateComment",
    RemovePostComment = "/po/removeComment",
    RemoveChatComment = "/dm/removeComment",
    CreateOrUpdatePostReaction = "/po/addReaction",
    CreateOrUpdateChatReaction = "/dm/addOrCreateReaction",
    RemovePostReaction = "/po/removeReaction",
    RemoveChatReaction = "/dm/removeReaction",
    CreateOrUpdatePostCommentReaction = "/po/addReactionToComment",
    CreateOrUpdateChatCommentReaction = "/dm/addOrUpdateReactionOnComment",
    RemovePostCommentReaction = "/po/removeReactionFromComment",
    RemoveChatCommentReaction = "/dm/removeReactionOnComment",
    SearchChatWithUser = "/dm/searchChatWithUser",
    SearchActiveUserChannelList = "/ch/channelActiveListWithLatestPostWithSearchText",
    SearchArchiveUserChannelList = "/ch/channelArchivedListWithLatestPostWithSearchText",

}