export enum GetEndpointUrl {
    Logout = "/logout",
    SelfProfile = "/user/profile",
    SelfProfileSideNav = "/user/sidebarNav",
    UserListNotBelongToChannel = "user/usersListNotBelongToChannelId",
    UserListNotBelongToDm = "user/usersListWhoDontBelongToTheDM",
    UserListNotBelongToProjectButBelongsToTeam="user/usersListWhoDontBelongToTheProjectButBelongToTheTeam",
    UsersListWhoDontBelongToTheTeam="user/usersListWhoDontBelongToTheTeam",
    CheckTeamNameAvailability = "/team/checkTeamNameExist",
    TeamListUserIsAdmin = "/team/teamListByAdminUID",
    CheckChannelNameAvailability = "/ch/chNameIsAvailable",
    ChannelBasicInfo = "/ch/channelBasicInfo",
    ChannelRecordingList = "/ch/getRecordingList",
    ChatRecordingList = "/dm/getRecordingList",
    GroupChatRecordingList = "/groupChat/getRecordingList",
    ChannelMemberInfoWithAdminFlagInfo = "/ch/channelInfoWithMemberAdminFlag",
    PublicAttachmentURL = "/getFile",
    GetChannelMedia = "/ch/getFile",
    GetProjectMedia = "/project/getFile",
    GetDocMedia = "/doc/getFile",
    GetDocAttachment = "/doc/getDocAttachment",
    GetChannelLatestPost = "/po/latestPosts",
    GetChatLatestMessage = "/dm/latestChat",
    GetGroupChatLatestMessage = "/groupChat/latestChat",
    GetNewPostIncludingCurrentPost = "/po/newPostsIncludingCurrent",
    GetNewChatIncludingCurrentChat = "/dm/newChatsIncludingCurrentChat",
    GetNewGroupChatIncludingCurrentChat = "/groupChat/newChatsIncludingCurrentChat",
    GetNewPostAfter = "/po/newPosts",
    GetNewChatAfter = "/dm/newChats",
    GetNewGroupChatAfter = "/groupChat/newChats",
    GetOldPostBefore = "/po/oldPosts",
    GetOldChatBefore = "/dm/oldChats",
    GetOldGroupChatBefore = "/groupChat/oldChats",
    GetChatMedia = "/dm/getFile",
    GetGroupChatMedia = "/groupChat/getFile",
    GetChannelRecordingMedia = "/ch/getRecordingURL",
    GetChatRecordingMedia = "/dm/getRecordingURL",
    GetGrpChatRecordingMedia = "/groupChat/getRecordingURL",
    GetChannelRecordingTranscript = "/ch/getRecordingTranscript",
    GetChatRecordingTranscript = "/dm/getRecordingTranscript",
    GetGrpChatRecordingTranscript = "/groupChat/getRecordingTranscript",
    GetOnlyPostText = "/po/getOnlyPostText",
    GetOnlyChatText = "/dm/getChatOnlyText",
    GetOnlyGroupChatText = "/groupChat/getChatOnlyText",
    GetUserStatuses = "/user/getAllUserEmojiStatusList",
    GetUserEmojiStatus = "/user/getActiveUserEmojiStatus",
    GetPostWithAllComments = "/po/allComments",
    GetChatWithAllComments = "/dm/chatWithAllComments",
    GetAllCommentOfDoc = "/doc/getCommentList",
    GetMqttConfig = "/config/mqttConfig",
    GetUserLatestChatList = "/dm/getLatestChatList",
    GetUserTeamList = "/team/teamListByUserUID",
    GetAllUser = "/user/allUsers",
    GetUserPrivateDocList = "/doc/getPrivateDoc",
    GetUserPublicDocList = "/doc/getPublicDoc",
    GetUserActiveChannelList = "/ch/userActiveChannelsWithLatestPost",
    GetAllActiveChannelList = "/ch/allActiveChannels",
    GetUserArchiveChannelList = "/ch/userArchiveChannelsWithLatestPost",
    GetTeamInfo = "/team/info",
    GetTeamProjectList = "/team/projectList",
    GetProjectMembers = "/project/memberWithAdminFlag",
    GetTeamMemberInfo = "/team/membersInfo",
    GetProjectMemberInfo = "/project/membersInfo",
    GetProjectInfo = "/project/info",
    GetProjectTaskList = "/project/taskList",
    GetProjectTaskListForKanban = "/project/taskListForKanban",
    GetUserTaskList = "/user/assignedTaskList",
    GetUserTaskListForKanban = "/user/assignedTaskListForKanban",
    GetProjectAttachments = "/project/attachments",
    projectListByAdminUID = "/project/projectListByAdminUID",
    GetTaskInfo = "/task/info",
    GetUserProjectList = "/user/userProjectList",
    GetDmGroupParticipants = "/groupChat/getDmParticipants",
    GetDocInfo = "/doc/getDocInfo",
    GetDocPermissions = "/doc/getDocPermissions",
    GlobalSearch = "/search/unifiedSearch/",
    GetMentionActivity= "/activity/mentions",
    GetCommentActivity= "/activity/comments",
    GetReactionsActivity= "/activity/reactions",
    GetUnifiedActivity= "/activity/unified",
    GetUserPosts = "/user/posts",
    UserRecordingList = "/user/recordingList",
    GetAdminTeamList = "/admin/getAllTeamList",
    GetAdminUserList = "/admin/getAllUsersList",
    GetAdminAdminList = "/admin/getAllAdminUsers",
    GetAdminInvitationList = "/admin/getAllInvitations",
    GetEmailConfig = "/admin/config/email",
    GoogleCalendarAuthUrl = "/integration/google-calendar/auth-url",
    GoogleCalendarStatus = "/integration/google-calendar/status",
    GoogleCalendarEvents = "/event/getEvents",

    // Webhooks (Admin)
    GetAllWebhooks = "/admin/webhooks",
    GetWebhookLogs = "/admin/webhooks", // append /{webhookId}/logs
    GetWebhookEventTypes = "/admin/webhooks/event-types",

    // GitHub (Admin)
    GetGitHubAuthUrl = "/admin/github/auth-url",
    GetGitHubStatus = "/admin/github/status",
    GetGitHubRateLimit = "/admin/github/rate-limit",
    GetGitHubRepos = "/admin/github/repos",
    GetGitHubLinkedRepos = "/admin/github/linked-repos", // append /{projectId}

    // GitHub (Task)
    GetGitHubTaskActivity = "/task/github-activity",
    GetGitHubSyncStatus = "/task/github-sync-status",
    GetGitHubSearchIssues = "/task/github-search-issues",
    GetGitHubSearchPRs = "/task/github-search-prs",

    // External Users (Admin)
    GetExternalUsers = "/admin/external-users",

    // Archive (Admin)
    GetArchivePolicies = "/admin/archive/policies",
    GetArchiveJobs = "/admin/archive/jobs",
    GetArchiveStats = "/admin/archive/stats",
}


export enum PostFileUploadURL {
    UploadFile = "/uploadFile",
}

export enum PostEndpointUrl {
    CreateTeam = "/team/createTeam",
    CreateProject = "/project/createProject",
    CreateChannel = "/ch/create",
    CreateDoc = "/doc/createDoc",
    UpdateDoc = "/doc/updateDoc",
    JoinChannel = "/ch/joinChannel",
    UpdateChannel = "/ch/updateInfo",
    RemoveProjectModerator = "/project/removeAdminRole",
    RemoveTeamModerator = "/team/removeAdminRole",
    RemoveChannelModerator = "/ch/removeModerator",
    RemoveChannelMember = "/ch/removeMember",
    RemoveProjectMember = "/project/removeMember",
    RemoveTeamMember = "/team/removeMember",
    AddChannelModerator = "/ch/addModerator",
    AddProjectModerator = "/project/addAdminRole",
    AddTeamAdminRole = "/team/addAdminRole",
    AddChannelMember = "/ch/addMember",
    AddProjectMember = "/project/addMember",
    AddTeamMember = "/team/addMember",
    RemoveTeam = "/admin/deleteTeam",
    UnDeletedTeam = "/admin/unDeleteTeam",
    AddDmMember = "/groupChat/addParticipant",
    AddFavChannel = "/user/addFavChannel",
    RemoveFavChannel = "/user/removeFavChannel",
    UpdateProjectNotification = "/user/updateUserProjectNotification",
    UpdateChannelNotification = "/user/updateUserChannelNotification",
    UpdateChatNotification = "/user/updateChatNotification",
    UpdateGroupChatNotification = "/user/updateGroupChatNotification",
    CreateChannelPost = "/po/createPost",
    CreateChatMessage = "/dm/createChat",
    CreateGroupChatMessage = "/groupChat/createChat",
    DeleteChannelPost = "/po/deletePost",
    DeleteChatMessage = "/dm/deleteChat",
    UpdateChannelPost = "/po/updatePost",
    UpdateChatMessage = "/dm/updateChat",
    UpdateGroupChatMessage = "/groupChat/updateChat",
    SearchUserAndChannel = "/user/searchUserAndChannelList",
    FwdMsgToChatOrChannel = "/user/fwdMessage",
    UpdateUserEmojiStatus = "/user/updateStatusEmojiStatus",
    ClearEmojiStatus = "/user/clearUserEmojiStatus",
    CreatePostComment = "/po/createComment",
    CreateChannelVideoCallToken = "/ch/getCallToken",
    CreateChatVideoCallToken = "/dm/getCallToken",
    CreateGroupChatVideoCallToken = "/groupChat/getCallToken",
    StartChannelCallRecording = "/ch/startCallRecording",
    StopChannelCallRecording = "/ch/stopCallRecording",
    StartDmCallRecording = "/dm/startCallRecording",
    StopDmCallRecording = "/dm/stopCallRecording",
    StartGrpCallRecording = "/groupChat/startCallRecording",
    StopGrpCallRecording = "/groupChat/stopCallRecording",
    DeleteChannelRecording = "/ch/deleteRecording", // append /{egressId}
    DeleteChatRecording = "/dm/deleteRecording", // append /{egressId}
    DeleteGroupChatRecording = "/groupChat/deleteRecording", // append /{egressId}
    CreateChatComment = "/dm/createComment",
    UpdatePostComment = "/po/updateComment",
    UpdateDocComment = "/doc/updateComment",
    UpdateDocPermissions = "/doc/updateDocPermissions",
    SearchUserForDoc = "/doc/searchUsers",
    RemoveDocComment = "/doc/removeComment",
    UpdateTaskComment = "/task/updateComment",
    UpdateChatComment = "/dm/updateComment",
    RemovePostComment = "/po/removeComment",
    RemoveChatComment = "/dm/removeComment",
    RemoveTaskComment = "/task/deleteTaskComment",
    CreateOrUpdatePostReaction = "/po/addReaction",
    CreateOrUpdateChatReaction = "/dm/addOrCreateReaction",
    RemovePostReaction = "/po/removeReaction",
    RemoveChatReaction = "/dm/removeReaction",
    CreateOrUpdatePostCommentReaction = "/po/addReactionToComment",
    CreateOrUpdateChatCommentReaction = "/dm/addOrUpdateReactionOnComment",
    CreateOrUpdateTaskCommentReaction = "/task/addReactionToComment",
    CreateOrUpdateDocCommentReaction = "/doc/addOrUpdateReactionOnComment",
    RemovePostCommentReaction = "/po/removeReactionFromComment",
    RemoveChatCommentReaction = "/dm/removeReactionOnComment",
    RemoveTaskCommentReaction = "/task/removeReactionFromComment",
    RemoveDocCommentReaction = "/doc/removeReactionOnComment",
    SearchChatWithUser = "/dm/searchChatWithUser",
    SearchActiveUserChannelList = "/ch/channelActiveListWithLatestPostWithSearchText",
    SearchArchiveUserChannelList = "/ch/channelArchivedListWithLatestPostWithSearchText",
    SearchPrivateDocList = "/doc/searchPrivate",
    SearchPublicDocList = "/doc/searchPublic",
    DeleteProject = "/project/deleteProject",
    UndeleteProject = "/project/unDeleteProject",
    UpdateTeamName = "/team/updateName",
    UpdateProjectName = "/project/updateName",
    AddAttachmentToProject = "/project/addAttachment",
    RemoveAttachmentToProject = "/project/removeAttachment",
    CreateTask = "/task/createTask",
    UpdateTaskName = "/task/updateTaskName",
    UpdateTaskStatus = "/task/updateTaskStatus",
    UpdateTaskPriority = "/task/updateTaskPriority",
    UpdateTaskLabel = "/task/updateTaskLabel",
    UpdateTaskDesc = "/task/updateTaskDesc",
    UpdateTaskStartDate = "/task/updateTaskStartDate",
    UpdateTaskDueDate = "/task/updateTaskDueDate",
    UpdateTaskAssignee = "/task/updateTaskAssignee",
    UnArchiveTask = "/task/undeleteTask",
    ArchiveTask = "/task/deleteTask",
    CreateSubTask = "/task/createSubTask",
    AddAttachmentToTask = "/task/addAttachmentToTask",
    CreateTaskComment = "/task/createCommentTask",
    CreateDocComment = "/doc/createComment",
    RemoveTaskAttachment = "/task/deleteTaskAttachment",
    UpdateUserProfile = "/updateUserProfile",
    UpdateUserTheme = "/updateUserTheme",
    DeleteDoc = "/doc/deleteDoc",
    UpdateFCMToken = "/user/updateFCMToken",
    GlobalSearch = "/search/unifiedSearch",
    CreateAdmin = "/admin/createAdmin",
    RemoveAdmin = "/admin/removeAdmin",
    DeactivateUser = "/admin/deactivateUser",
    ActivateUser = "/admin/activateUser",
    Logout = "/logout",
    PublishChannelTyping = "/ch/publishChannelTyping",
    PublishChatTyping = "/dm/publishChatTyping",
    AddInvitation = "/admin/addInvitation",
    DeleteInvitation = "/admin/deleteInvitation/",
    ResendInvitation = "/admin/resendInvitation",
    GetEmailConfig = "/admin/config/email",
    UpdateEmailConfig = "/admin/config/email",
    UploadEmailLogo = "/admin/config/email/logo",
    DeleteEmailLogo = "/admin/config/email/logo",
    GoogleCalendarUnlink = "/integration/google-calendar/unlink",
    CreateCalendarEvent = "/event/createEvent",
    UpdateCalendarEvent = "/event/updateEvent",
    DeleteCalendarEvent = "/event/deleteEvent",
    LeaveEvent = "/event/leaveEvent",
    UpdateGoogleCalendarSyncTask = "/integration/google-calendar/sync-task",

    // Webhooks (Admin)
    CreateWebhook = "/admin/webhooks",
    UpdateWebhook = "/admin/webhooks", // append /{webhookId} — use PUT
    DeleteWebhook = "/admin/webhooks", // append /{webhookId} — use DELETE
    RegenerateWebhookToken = "/admin/webhooks", // append /{webhookId}/regenerate-token
    RegenerateWebhookSecret = "/admin/webhooks", // append /{webhookId}/regenerate-secret
    TestWebhook = "/admin/webhooks", // append /{webhookId}/test

    // GitHub (Admin)
    GitHubCallback = "/admin/github/callback",
    GitHubDisconnect = "/admin/github/disconnect",
    GitHubLinkRepo = "/admin/github/link-repo",
    GitHubUnlinkRepo = "/admin/github/unlink-repo", // append /{linkId} — use DELETE
    GitHubImportIssues = "/admin/github/import-issues", // append /{linkId}
    GitHubImportPRs = "/admin/github/import-prs", // append /{linkId}
    GitHubUpdateAutomationRules = "/admin/github/links/automation-rules", // append /{linkId}
    GitHubUpdateBranchFormat = "/admin/github/links/branch-format", // append /{linkId}

    // GitHub (Task)
    GitHubLinkTask = "/task/github-link",
    GitHubUnlinkTask = "/task/github-unlink",
    GitHubCreateBranch = "/task/create-branch",
    GitHubRetrySync = "/task/github-retry-sync",
    GitHubRefresh = "/task/github-refresh",
    GitHubCreatePR = "/task/github-create-pr",
    GitHubBulkLink = "/task/github-bulk-link",
    GitHubBulkUnlink = "/task/github-bulk-unlink",

    // External Users (Admin)
    UnlinkExternalUser = "/admin/external-users/unlink",

    // Archive (Admin)
    UpdateArchivePolicy = "/admin/archive/policies", // append /{entityType} — use PUT
    RunArchiveJob = "/admin/archive/run", // append /{entityType}
    RestoreArchiveItems = "/admin/archive/restore",
    UndoArchiveJob = "/admin/archive/undo", // append /{jobId}
}