"use client"

/**
 * The evidence pack, as a document somebody can read.
 *
 * WHY THIS EXISTS. The pack was already assembled, fingerprinted and honest about
 * its own limits — the chain recomputation, what each agent was told, a manifest
 * digesting every section, and a plain statement of what it does not prove. It
 * was available as `onecamp-evidence-pack.json` and nothing else. Nobody hands an
 * auditor a JSON file. The work of assembling the argument was done and then
 * delivered in the one form its reader cannot use.
 *
 * A READING, NOT A REPLACEMENT. The fingerprint is a digest of those exact JSON
 * bytes, so a printed page cannot be verified and must never look as though it
 * can. The document says which pack it is a reading of, keeps the verification
 * steps and the limits in full rather than summarising them, and puts the file
 * download next to the fingerprint it belongs to.
 *
 * GENERIC OVER SECTIONS on purpose. Sections are contributed by whichever
 * packages an edition links, so the AI-free build has fewer and a new subsystem
 * adds one without touching this file. The manifest is the index and it travels
 * inside the same document, so this renders what the pack says it contains rather
 * than what this component was written knowing about.
 */

import React from "react"
import { Button } from "@/components/ui/button"
import { Download, ShieldCheck, ShieldAlert } from "@/lib/icons"
import type { EvidencePack, EvidenceManifestEntry } from "@/services/settingsService"

/** A section title a person reads, from an id a programmer wrote. */
export function sectionTitle(id: string): string {
    const words = id.replace(/[_-]+/g, " ").trim()
    if (!words) return "Section"
    return words.charAt(0).toUpperCase() + words.slice(1)
}

/**
 * The rows of a section, whatever shape it arrived in.
 *
 * A section is `unknown` by the time it reaches here. An array is rows; an object
 * is one row; anything else is a value worth showing rather than dropping. The
 * alternative — rendering only what typechecks — silently omits a contributed
 * section, which is the one failure an evidence document must not have.
 */
export function sectionRows(value: unknown): Array<Record<string, unknown>> {
    if (Array.isArray(value)) {
        return value.map((v) => (v !== null && typeof v === "object" ? (v as Record<string, unknown>) : { value: v }))
    }
    if (value !== null && typeof value === "object") return [value as Record<string, unknown>]
    if (value === null || value === undefined) return []
    return [{ value }]
}

/** Column order taken from the rows themselves, first seen first. */
export function sectionColumns(rows: Array<Record<string, unknown>>): string[] {
    const seen: string[] = []
    for (const row of rows) {
        for (const key of Object.keys(row)) {
            if (!seen.includes(key)) seen.push(key)
        }
    }
    return seen
}

/** A cell, printable. Objects are shown as compact JSON rather than [object Object]. */
export function cellText(value: unknown): string {
    if (value === null || value === undefined) return ""
    if (typeof value === "object") return JSON.stringify(value)
    return String(value)
}

function Meta({ label, value }: { label: string; value: React.ReactNode }) {
    return (
        <div className="min-w-0">
            <dt className="text-xs uppercase tracking-wide text-muted-foreground">{label}</dt>
            <dd className="mt-0.5 break-words text-sm text-foreground">{value}</dd>
        </div>
    )
}

export const EvidencePackView: React.FC<{
    pack: EvidencePack
    /** Saves the JSON the fingerprint belongs to. */
    onDownload?: () => void
}> = ({ pack, onDownload }) => {
    const v = pack.integrity.chain_verification
    const manifest: EvidenceManifestEntry[] = pack.integrity.manifest ?? []

    return (
        <article className="mx-auto max-w-4xl px-4 py-8 print:max-w-none print:px-0 print:py-0">
            <header className="border-b border-border pb-6">
                <p className="text-xs uppercase tracking-wide text-muted-foreground">
                    {pack.pack.product} · Evidence pack
                </p>
                <h1 className="mt-1 text-2xl font-semibold tracking-tight">
                    What happened, when, by whom, and under which policy
                </h1>
                <dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                    <Meta label="Window" value={`${fmt(pack.pack.from)} to ${fmt(pack.pack.to)}`} />
                    <Meta label="Generated" value={fmt(pack.pack.generated_at)} />
                    <Meta label="Generated by" value={pack.pack.generated_by || "unknown"} />
                    <Meta
                        label="Pack fingerprint"
                        value={<span className="font-mono text-xs">{pack.integrity.pack_fingerprint}</span>}
                    />
                </dl>
            </header>

            {/* The verdict first. It is the one thing a reader came for. */}
            <section className="mt-8">
                <h2 className="text-base font-semibold">Integrity</h2>
                {v ? (
                    <div
                        className={`mt-3 flex items-start gap-3 rounded-lg border p-4 ${
                            v.ok ? "border-success/40 bg-success/5" : "border-destructive/40 bg-destructive/5"
                        }`}
                    >
                        {v.ok ? (
                            <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-success" aria-hidden="true" />
                        ) : (
                            <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-destructive" aria-hidden="true" />
                        )}
                        <div className="min-w-0 text-sm">
                            <p className="font-medium">{v.message}</p>
                            <p className="mt-1 text-muted-foreground">
                                {v.checked} row{v.checked === 1 ? "" : "s"} recomputed
                                {v.redacted ? `, ${v.redacted} taken at their word after redaction` : ""}
                                {v.partial ? ". A window was checked, not the whole log." : "."}
                            </p>
                        </div>
                    </div>
                ) : (
                    <p className="mt-3 text-sm text-muted-foreground">
                        No chain verification travelled with this pack.
                    </p>
                )}
            </section>

            {/* The manifest, because a digest per section is what lets a reader
                check this document against the file without trusting either. */}
            <section className="mt-8">
                <h2 className="text-base font-semibold">Contents</h2>
                <div className="mt-3 overflow-x-auto rounded-lg border border-border">
                    <table className="w-full min-w-[34rem] border-collapse text-left text-sm">
                        <thead>
                            <tr className="border-b border-border bg-muted/40">
                                <th scope="col" className="px-3 py-2 font-medium">Section</th>
                                <th scope="col" className="px-3 py-2 font-medium">Rows</th>
                                <th scope="col" className="px-3 py-2 font-medium">Describes</th>
                                <th scope="col" className="px-3 py-2 font-medium">SHA-256</th>
                            </tr>
                        </thead>
                        <tbody>
                            {manifest.map((m) => (
                                <tr key={m.section} className="border-b border-border last:border-0 align-top">
                                    <th scope="row" className="px-3 py-2 font-normal">{sectionTitle(m.section)}</th>
                                    <td className="px-3 py-2 tabular-nums">{m.rows}</td>
                                    <td className="px-3 py-2 text-muted-foreground">{m.describes}</td>
                                    <td className="px-3 py-2 font-mono text-xs break-all">{m.sha256}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </section>

            {/* Every section the pack declared, in the manifest's order. */}
            {manifest.map((m) => {
                const rows = sectionRows(pack.sections?.[m.section])
                const columns = sectionColumns(rows)
                return (
                    <section key={m.section} className="mt-8 break-inside-avoid">
                        <h2 className="text-base font-semibold">{sectionTitle(m.section)}</h2>
                        <p className="mt-0.5 text-sm text-muted-foreground">{m.describes}</p>
                        {rows.length === 0 ? (
                            <p className="mt-3 text-sm text-muted-foreground">
                                Nothing in this window.
                            </p>
                        ) : (
                            <div className="mt-3 overflow-x-auto rounded-lg border border-border">
                                <table className="w-full min-w-[34rem] border-collapse text-left text-xs">
                                    <thead>
                                        <tr className="border-b border-border bg-muted/40">
                                            {columns.map((c) => (
                                                <th key={c} scope="col" className="px-3 py-2 font-medium">
                                                    {sectionTitle(c)}
                                                </th>
                                            ))}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {rows.map((row, i) => (
                                            <tr key={i} className="border-b border-border last:border-0 align-top">
                                                {columns.map((c) => (
                                                    <td key={c} className="px-3 py-2 break-words">
                                                        {cellText(row[c])}
                                                    </td>
                                                ))}
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </section>
                )
            })}

            {/* Verbatim, both of them. Summarising the verification steps would
                leave a reader trusting the summary, and softening the limits is
                the failure the limits exist to prevent. */}
            <section className="mt-10 break-inside-avoid">
                <h2 className="text-base font-semibold">How to verify this</h2>
                <ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-muted-foreground">
                    {pack.how_to_verify?.map((step) => <li key={step}>{step}</li>)}
                </ol>
            </section>

            <section className="mt-8 break-inside-avoid">
                <h2 className="text-base font-semibold">What this does not prove</h2>
                <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-muted-foreground">
                    {pack.limits?.map((limit) => <li key={limit}>{limit}</li>)}
                </ul>
            </section>

            <footer className="mt-10 border-t border-border pt-6 text-sm text-muted-foreground">
                <p>
                    This page is a reading of pack{" "}
                    <span className="font-mono text-xs">{pack.integrity.pack_fingerprint}</span>. The
                    fingerprint is a digest of the JSON, so verification is done against the file and
                    not against this page or a print of it.
                </p>
                {onDownload && (
                    <Button variant="outline" size="sm" className="mt-4 gap-2 print:hidden" onClick={onDownload}>
                        <Download className="h-4 w-4" />
                        Download the file this reads
                    </Button>
                )}
            </footer>
        </article>
    )
}

/** Dates as a reader reads them, falling back to the raw value rather than "Invalid Date". */
function fmt(iso: string): string {
    const d = new Date(iso)
    if (Number.isNaN(d.getTime())) return iso || "unknown"
    return d.toISOString().replace("T", " ").replace(/\.\d+Z$/, "Z")
}

export default EvidencePackView
